// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddpndaofmngjhpgwqkzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkcG5kYW9mbW5namhwZ3dxa3p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NzM1ODcsImV4cCI6MjA2NTA0OTU4N30.vyG0oX6lP70AM2Ur7nyJ-NSY5F6VIc8rKKDshaPp_Mc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);